// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "../ui.h"
#include <ArduinoJson.h>
#include <vector>
#include <string>

struct Alarm {
    std::string time;
    std::string label;
    bool enabled;
};

extern std::vector<Alarm> alarms;

lv_obj_t * ui_Alarm = NULL;
lv_obj_t * ui_Alarm_container = NULL;
lv_obj_t * ui_Set_alarm = NULL;
lv_obj_t * ui_Alarm_Comp = NULL;
lv_obj_t * ui_Alarm_Comp1 = NULL;
lv_obj_t * ui_Alarm_Comp2 = NULL;
lv_obj_t * ui_Alarm_Comp3 = NULL;
lv_obj_t * ui_Scrolldots5 = NULL;
lv_obj_t * ui_No_alarm = NULL;
// event funtions
void ui_event_Alarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        // Request alarm list when Alarm screen opens
        JsonDocument request;
        request["request"] = "alarms";
        String out;
        serializeJson(request, out);
        Serial.println(out);

        upanim_Animation(ui_Set_alarm, 100);
        // Removed animations for dynamic alarm components
        scrolldot_Animation(ui_Scrolldots5, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Weather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Weather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Alarm_screen_init(void)
{
    ui_Alarm = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Alarm, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Alarm, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_container = lv_obj_create(ui_Alarm);
    lv_obj_set_width(ui_Alarm_container, lv_pct(100));
    lv_obj_set_height(ui_Alarm_container, lv_pct(100));
    lv_obj_set_align(ui_Alarm_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Alarm_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Alarm_container, LV_OBJ_FLAG_SCROLLABLE);  // Make it scrollable for dynamic content

    ui_Set_alarm = ui_Small_Label_create(ui_Alarm_container);
    lv_obj_set_x(ui_Set_alarm, 0);
    lv_obj_set_y(ui_Set_alarm, 17);
    lv_obj_set_align(ui_Set_alarm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Set_alarm, "Set alarm");
    lv_obj_set_style_text_color(ui_Set_alarm, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Set_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Dynamic alarm components
    extern std::vector<Alarm> alarms;
    int y_pos = 43;
    for (size_t i = 0; i < alarms.size(); ++i) {
        lv_obj_t *alarm_comp = ui_Alarm_Comp_create(ui_Alarm_container);
        lv_obj_set_x(alarm_comp, 0);
        lv_obj_set_y(alarm_comp, y_pos);

        lv_label_set_text(ui_comp_get_child(alarm_comp, UI_COMP_ALARM_COMP_ALARM_NUM2), alarms[i].time.c_str());
        lv_label_set_text(ui_comp_get_child(alarm_comp, UI_COMP_ALARM_COMP_PERIOD), alarms[i].label.c_str());

        if (alarms[i].enabled) {
            lv_obj_add_state(ui_comp_get_child(alarm_comp, UI_COMP_ALARM_COMP_SWITCH1), LV_STATE_CHECKED);
        } else {
            lv_obj_clear_state(ui_comp_get_child(alarm_comp, UI_COMP_ALARM_COMP_SWITCH1), LV_STATE_CHECKED);
        }

        y_pos += 85;  // Adjust spacing
    }

    // Fallback for empty alarm list
    if (alarms.empty()) {
        ui_No_alarm = ui_Small_Label_create(ui_Alarm_container);
        lv_obj_set_x(ui_No_alarm, 0);
        lv_obj_set_y(ui_No_alarm, 43);
        lv_obj_set_align(ui_No_alarm, LV_ALIGN_TOP_MID);
        lv_label_set_text(ui_No_alarm, "No alarm");
        lv_obj_set_style_text_color(ui_No_alarm, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(ui_No_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    ui_Scrolldots5 = ui_Scrolldots_create(ui_Alarm);
    lv_obj_set_x(ui_Scrolldots5, 0);
    lv_obj_set_y(ui_Scrolldots5, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D2), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D3), 20);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D3), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D4), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D4), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D5), 40);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D5), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 50);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);

}

void ui_Alarm_screen_destroy(void)
{
    if(ui_Alarm) lv_obj_del(ui_Alarm);

    // NULL screen variables
    ui_Alarm = NULL;
    ui_Alarm_container = NULL;
    ui_Set_alarm = NULL;
    ui_Alarm_Comp = NULL;
    ui_Alarm_Comp1 = NULL;
    ui_Alarm_Comp2 = NULL;
    ui_Alarm_Comp3 = NULL;
    ui_Scrolldots5 = NULL;
    ui_No_alarm = NULL;

}
