// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "../ui.h"
#include <ArduinoJson.h>

extern JsonDocument metrics;

lv_obj_t * ui_Call = NULL;
lv_obj_t * ui_CPU_Gauge = NULL;
lv_obj_t * ui_CPU_Label = NULL;
lv_obj_t * ui_Scrolldots1 = NULL;
// event funtions
void ui_event_Call(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        // Update CPU gauge
        if (metrics["cpu"].is<String>()) {
            String cpu_str = metrics["cpu"];
            int cpu_value = cpu_str.toInt();
            lv_arc_set_value(ui_CPU_Gauge, cpu_value);
            lv_label_set_text_fmt(ui_CPU_Label, "CPU: %d%%", cpu_value);
        }
        scrolldot_Animation(ui_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Chat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Chat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Call_screen_init(void)
{
    ui_Call = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Call, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Call, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Call, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    // CPU Gauge - using arc widget as a gauge
    ui_CPU_Gauge = lv_arc_create(ui_Call);
    lv_obj_set_size(ui_CPU_Gauge, 200, 200);
    lv_obj_center(ui_CPU_Gauge);
    lv_obj_set_y(ui_CPU_Gauge, -20);
    lv_arc_set_range(ui_CPU_Gauge, 0, 100);
    lv_arc_set_value(ui_CPU_Gauge, 0);
    lv_arc_set_bg_angles(ui_CPU_Gauge, 135, 45); // Background arc from 135° to 45°
    lv_arc_set_angles(ui_CPU_Gauge, 135, 135);   // Start with indicator at 135°
    lv_obj_set_style_arc_color(ui_CPU_Gauge, lv_color_hex(0xE63431), LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(ui_CPU_Gauge, 8, LV_PART_INDICATOR);
    lv_obj_set_style_arc_color(ui_CPU_Gauge, lv_color_hex(0x000746), LV_PART_MAIN);
    lv_obj_set_style_arc_width(ui_CPU_Gauge, 4, LV_PART_MAIN);

    // CPU Label
    ui_CPU_Label = lv_label_create(ui_Call);
    lv_obj_set_style_text_font(ui_CPU_Label, &lv_font_montserrat_20, 0);
    lv_obj_set_style_text_color(ui_CPU_Label, lv_color_hex(0x000746), 0);
    lv_label_set_text(ui_CPU_Label, "CPU: 0%");
    lv_obj_align(ui_CPU_Label, LV_ALIGN_BOTTOM_MID, 0, -40);

    ui_Scrolldots1 = ui_Scrolldots_create(ui_Call);
    lv_obj_set_x(ui_Scrolldots1, 0);
    lv_obj_set_y(ui_Scrolldots1, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 11);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Call, ui_event_Call, LV_EVENT_ALL, NULL);

}

void ui_Call_screen_destroy(void)
{
    if(ui_Call) lv_obj_del(ui_Call);

    // NULL screen variables
    ui_Call = NULL;
    ui_CPU_Gauge = NULL;
    ui_CPU_Label = NULL;
    ui_Scrolldots1 = NULL;

}
